---

root: true

env:
  es6: true
  browser: true
  mocha: true
  node: true

rules:
  arrow-body-style: 2
  arrow-parens: [2, always]
  arrow-spacing: 2
  block-scoped-var: 2
  block-spacing: [2, always]
  brace-style: [2, 1tbs]
  comma-dangle: 0
  curly: [2, all]
  dot-location: [2, property]
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  handle-callback-err: 2
  indent: [2, tab]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  keyword-spacing: [2, {before: true, after: true}]
  linebreak-style: [2, unix]
  no-catch-shadow: 2
  no-confusing-arrow: 2
  no-console: 0
  no-control-regex: 0
  no-duplicate-imports: 2
  no-else-return: 2
  no-implicit-globals: 2
  no-multi-spaces: 2
  no-multiple-empty-lines: [2, { "max": 1 }]
  no-shadow: 2
  no-template-curly-in-string: 2
  no-trailing-spaces: 2
  no-unsafe-negation: 2
  no-useless-computed-key: 2
  no-useless-return: 2
  object-curly-spacing: [2, never]
  padded-blocks: [2, never]
  prefer-const: 2
  quote-props: [2, as-needed]
  quotes: [2, double, avoid-escape]
  semi-style: [2, last]
  semi: [2, always]
  space-before-blocks: 2
  space-before-function-paren: [2, never]
  space-in-parens: [2, never]
  space-infix-ops: 2
  spaced-comment: [2, always]
  strict: 2
  template-curly-spacing: 2
  yoda: 2

globals:
  log: false

extends: eslint:recommended
