extends: stylelint-config-standard

rules:
  indentation: tab
  # complains about FontAwesome
  font-family-no-missing-generic-family-keyword:
  # needs a lot of refactoring to be enabled
  no-descending-specificity:

  # we have autoprefixer
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  property-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true

  # renaming would break existing themes
  selector-class-pattern: null
  selector-id-pattern: null
