// Action Types
export const INITIAL_DATA_RECEIVED = 'chat/INITIAL_DATA_RECEIVED';
export const JOINED_NETWORK = 'chat/JOINED_NETWORK';
export const LEFT_NETWORK = 'chat/LEFT_NETWORK';
export const JOINED_CHANNEL = 'chat/JOINED_CHANNEL';
export const LEFT_CHANNEL = 'chat/LEFT_CHANNEL';
export const RECEIVED_CHANNEL_USERS = 'chat/RECEIVED_CHANNEL_USERS';
export const REQUEST_MORE = 'chat/REQUEST_MORE';
export const RECEIVED_MORE = 'chat/RECEIVED_MORE';
export const CHANGE_ACTIVE_CHANNEL = 'chat/CHANGE_ACTIVE_CHANNEL';
export const CHANGE_ACTIVE_WINDOW = 'chat/CHANGE_ACTIVE_WINDOW';
export const MESSAGE_RECEIVED = 'chat/MESSAGE_RECEIVED';
export const TOPIC_CHANGED = 'chat/TOPIC_CHANGED';
export const CHANNEL_USERS_INVALIDATED = 'chat/CHANNEL_USERS_INVALIDATED';
export const REQUEST_NAMES = 'chat/REQUEST_NAMES';
export const CLEAR_CHANNEL = 'chat/CLEAR_CHANNEL';

export const NICK_CHANGED = 'chat/NICK_CHANGED';
