name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Node on ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macOS-latest
          - windows-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - name: Install
        run: yarn --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Test
        run: yarn test
