name: Release

permissions:
  contents: read
  id-token: write

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  release:
    name: Release workflow

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          # TODO: we should use node-version-file but the version of npm with node 22 has issues updating to the latest version
          # https://github.com/nodejs/node/issues/62425
          node-version: "24"
          registry-url: "https://registry.npmjs.org/"

      - name: Install
        run: yarn --frozen-lockfile --non-interactive

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Test
        run: yarn test

      - name: Publish latest
        if: "!contains(github.ref, '-')"
        run: npm publish --tag latest --provenance

      - name: Publish next
        if: contains(github.ref, '-')
        run: npm publish --tag next --provenance

      - name: Remove next tag
        if: "!contains(github.ref, '-')"
        run: npm dist-tag rm thelounge next || true
